.prepare_env: &prepare_env
  - |
    function install_texlive() {
      if [[ -n "${APT_MIRROR:-}" ]]; then
        sed -i "s:deb.debian.org:${APT_MIRROR}:" /etc/apt/sources.list
        sed -i "s:security.debian.org:${APT_MIRROR}:" /etc/apt/sources.list
        sed -i 's:main$:main non-free contrib:;' /etc/apt/sources.list
      fi
      apt-get update
      local -a pkgs
      pkgs+=(graphviz)
      pkgs+=(texlive-fonts-extra)
      pkgs+=(texlive-fonts-recommended)
      pkgs+=(texlive-lang-chinese)
      pkgs+=(texlive-latex-extra)
      pkgs+=(texlive-latex-recommended)
      pkgs+=(texlive-plain-generic)
      pkgs+=(texlive-xetex)
      apt-get install --no-install-recommends -y "${pkgs[@]}"
    }
    install_texlive

build:
  stage: build
  artifacts:
    name: pdf
    paths:
      - ./*.pdf
    expire_in: 1 week
  script:
    - *prepare_env
    - xelatex c11.tex
    - xelatex c11.tex
  tags:
    - xelatex
  image: debian:bullseye
